name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank for **@${{ github.actor }}** your issue! Wea re glad you contributed!"
        pr-message: "Thanks you **@${{ github.actor }}** for your first pull Request!"
